#ifndef DEFINE_HPP
#define DEFINE_HPP

/* PASS message  */

# define ERR_NEEDMOREPARAMS 461
# define ERR_ALREADYREGISTERED 462
# define ERR_PASSWDMISMATCH 464

/*  NICK message */

# define ERR_NONICKNAMEGIVEN 431
# define ERR_ERRONEUSNICKNAME 432
# define ERR_NICKNAMEINUSE 433
# define ERR_NICKCOLLISION 436

/*	USER mesage	*/

# define ERR_NEEDMOREPARAMS 461
# define ERR_ALREADYREGISTERED 462

/*	JOIN message */

# define ERR_NEEDMOREPARAMS 461
# define ERR_NOSUCHCHANNEL 403
# define ERR_TOOMANYCHANNELS 405
# define ERR_BADCHANNELKEY 475
# define ERR_BANNEDFROMCHAN 474
# define ERR_CHANNELISFULL 471
# define ERR_INVITEONLYCHAN 473
# define ERR_BADCHANMASK 476
# define RPL_TOPIC 332
# define RPL_TOPICWHOTIME 333
# define RPL_NAMREPLY 353
# define RPL_ENDOFNAMES 366

/*	TOPIC message	*/

# define ERR_NEEDMOREPARAMS 461
# define ERR_NOSUCHCHANNEL 403
# define ERR_NOTONCHANNEL 442
# define ERR_CHANOPRIVSNEEDED 482
# define RPL_NOTOPIC 331
# define RPL_TOPIC 332
# define RPL_TOPICWHOTIME 333

/* INVITE message	*/

# define RPL_INVITING 341
# define ERR_NEEDMOREPARAMS 461
# define ERR_NOSUCHCHANNEL 403
# define ERR_NOTONCHANNEL 442
# define ERR_CHANOPRIVSNEEDED 482
# define ERR_USERONCHANNEL 443

/*	KICK message	*/

# define ERR_NEEDMOREPARAMS 461
# define ERR_NOSUCHCHANNEL 403
# define ERR_CHANOPRIVSNEEDED 482
# define ERR_USERNOTINCHANNEL 441
# define ERR_NOTONCHANNEL 442
# define ERR_BADCHANMASK 476

/*	PRIVMSG message	*/
# define ERR_NOSUCHNICK 401
# define ERR_NOSUCHSERVER 402
# define ERR_CANNOTSENDTOCHAN 404
# define ERR_TOOMANYTARGETS 407
# define ERR_NORECIPIENT 411
# define ERR_NOTEXTTOSEND 412
# define ERR_NOTOPLEVEL 413
# define ERR_WILDTOPLEVEL 414
# define RPL_AWAY 301

/*	WHO message	*/
# define RPL_WHOREPLY 352
# define RPL_ENDOFWHO 315


/*	KILL message	*/

# define ERR_NOSUCHSERVER 402
# define ERR_NEEDMOREPARAMS 461
# define ERR_NOPRIVILEGES 481
# define ERR_NOPRIVS 723

/*	NUMERICS	*/

# define RPL_WELCOME 001
# define RPL_LIST 322


#endif
